"""
STACD Catalog Export Configuration
Supports both STAC (datasets) and STACD (DAGs/algorithms) catalogs
"""
import os
from pathlib import Path

# PATHS
AIRFLOW_HOME = os.getenv("AIRFLOW_HOME", os.path.expanduser("~/airflow"))
DB_PATH = Path(AIRFLOW_HOME) / "stacd" / "database" / "stacd_recompute.db"
CATALOG_OUTPUT_DIR = Path.home() / "stacd_catalog"

# Ensure output directories exist
CATALOG_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
(CATALOG_OUTPUT_DIR / "datasets").mkdir(exist_ok=True)
(CATALOG_OUTPUT_DIR / "dags").mkdir(exist_ok=True)

# BASE URLs
CATALOG_BASE_URL = "http://localhost:8002"
STAC_BROWSER_URL = "http://localhost:8080"  # STAC Browser
STACD_BROWSER_URL = "http://localhost:8081"  # STACD Browser (to be built)
GEE_BASE_URL = "https://code.earthengine.google.com/?asset="

# CATALOG METADATA
ROOT_CATALOG_CONFIG = {
    "id": "stacd-core-stack-root",
    "title": "STACD CoRE Stack - Root Catalog",
    "description": "Root catalog providing access to both STAC (datasets) and STACD (workflows) browsers",
    "stac_version": "1.0.0",
    "type": "Catalog"
}

STAC_CATALOG_CONFIG = {
    "id": "stacd-datasets",
    "title": "STACD Datasets - STAC Browser",
    "description": "Geospatial datasets generated by STACD workflows. Browse by location hierarchy.",
    "stac_version": "1.0.0",
    "type": "Catalog"
}

STACD_CATALOG_CONFIG = {
    "id": "stacd-workflows",
    "title": "STACD Workflows - STACD Browser",
    "description": "Browse DAG structures, algorithms, and execution lineage. STACD-specific catalog.",
    "stac_version": "1.0.0",
    "type": "Catalog"
}

# EXTENSIONS
STACD_EXTENSION_SCHEMA = "https://github.com/saharsh-laud/stacd-spec/v1.0.0/schema.json"

# DATASET TYPE MAPPINGS
DATASET_TYPE_TITLES = {
    "MWS_Boundaries": "Micro-Watershed Boundaries",
    "LULC_Raster": "Land Use Land Cover Raster",
    "LULC_Vector": "Land Use Land Cover Vector",
    "Terrain_Raster": "Terrain Classification Raster",
    "Terrain_Vector": "Terrain Classification Vector",
    "Terrain_LULC_Vector_Slope": "Terrain-LULC Intersection (Slope)",
    "Terrain_LULC_Vector_Plain": "Terrain-LULC Intersection (Plain)"
}

DATASET_TYPE_ROLES = {
    "MWS_Boundaries": ["data", "boundary"],
    "LULC_Raster": ["data", "land-cover"],
    "LULC_Vector": ["data", "vector", "land-cover"],
    "Terrain_Raster": ["data", "terrain"],
    "Terrain_Vector": ["data", "vector", "terrain"],
    "Terrain_LULC_Vector_Slope": ["data", "vector", "analysis"],
    "Terrain_LULC_Vector_Plain": ["data", "vector", "analysis"]
}

# SPATIAL EXTENTS
SPATIAL_EXTENTS = {
    "jharkhand": {
        "dumka": {
            "masalia": {
                "bbox": [87.2, 24.2, 87.4, 24.4],
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [[[87.2, 24.2], [87.4, 24.2], [87.4, 24.4], [87.2, 24.4], [87.2, 24.2]]]
                }
            }
        }
    }
}

DEFAULT_BBOX = [85.0, 21.0, 89.0, 26.0]

# TEMPORAL SETTINGS
DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%SZ"

print(f"✓ Config loaded")
print(f"  Database: {DB_PATH}")
print(f"  Output: {CATALOG_OUTPUT_DIR}")
print(f"  STAC URL: {CATALOG_BASE_URL}")
print(f"  STACD Browser: {STACD_BROWSER_URL}")
