"""
Simple Docker Runner for STACD
Executes Python functions inside Docker containers with TRUE LIVE LOG STREAMING
"""
import docker
import json
import os
import sys
import inspect

def run_in_docker(image, module_path, function_name, function_params):
    """
    Run a Python function in a Docker container with live log streaming

    Args:
        image: Docker image name (e.g., 'stacd-backend:latest')
        module_path: Python module (e.g., 'computing.lulc.lulc_v3_clip_river_basin')
        function_name: Function to call (e.g., 'lulc_river_basin')
        function_params: Dict of parameters to pass to function

    Returns:
        list: Asset IDs generated by the function
    """

    client = docker.from_env()

    print(f"🐳 Docker Execution Starting...")
    print(f"   Image: {image}")
    print(f"   Module: {module_path}")
    print(f"   Function: {function_name}")
    print(f"   Params: {function_params}")
    print("="*60)
    sys.stdout.flush()  # Force immediate output

    # Insert generic function signature filtering!
    # This code will run inside the container
    python_code = f"""
import sys
import json
import ee
import inspect
from datetime import datetime as dt

# Initialize Earth Engine
ee.Initialize(project='ee-saharshlaud')

# Import and execute function
from {module_path} import {function_name}

params = {function_params}

# Filter only valid keyword arguments
sig = inspect.signature({function_name})
accepted_args = set(sig.parameters.keys())
filtered_params = {{k: v for k, v in params.items() if k in accepted_args}}

result = {function_name}(**filtered_params)

# Handle different return types
if isinstance(result, str):
    asset_ids = [result]
elif isinstance(result, list):
    asset_ids = result
elif isinstance(result, dict) and 'asset_ids' in result:
    asset_ids = result['asset_ids']
elif isinstance(result, dict) and 'asset_id' in result:
    asset_ids = [result['asset_id']]
else:
    asset_ids = []

# Build STAC spec for each asset
stac_assets = {{}}
for i, aid in enumerate(asset_ids):
    stac_assets[aid] = {{
        "href": f"https://code.earthengine.google.com/?asset={{aid}}",
        "type": "image/tiff; application=geotiff",
        "title": f"GEE Asset {{i+1}}",
        "roles": ["data"],
        "gee:asset_id": aid
    }}

state = params.get('state', 'unknown')
district = params.get('district', 'unknown')
block = params.get('block', 'unknown')
start_year = params.get('start_year')

stac_spec = {{
    "stac_version": "1.0.0",
    "stac_extensions": ["https://github.com/saharsh-laud/stacd-spec/v1.0.0/schema.json"],
    "type": "Feature",
    "id": f"{{state}}_{{district}}_{{block}}_{function_name}_docker",
    "geometry": {{
        "type": "Polygon",
        "coordinates": [[[85.0, 21.0], [89.0, 21.0], [89.0, 26.0], [85.0, 26.0], [85.0, 21.0]]]
    }},
    "bbox": [85.0, 21.0, 89.0, 26.0],
    "properties": {{
        "datetime": f"{{start_year}}-07-01T00:00:00Z" if start_year else dt.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "title": f"{function_name} output for {{block}}, {{district}}, {{state}}",
        "stacd:algorithm": "{function_name}",
        "stacd:state": state,
        "stacd:district": district,
        "stacd:block": block,
        "stacd:start_year": str(start_year) if start_year else None,
        "stacd:hosting_platform": "GEE"
    }},
    "assets": stac_assets,
    "links": []
}}

# Output as JSON on a separate line with marker
print("===RESULT_JSON_START===", flush=True)
output = {{
    'status': 'success',
    'asset_ids': asset_ids,
    'hosting_platform': 'GEE',
    'stac_spec': stac_spec
}}
print(json.dumps(output), flush=True)
print("===RESULT_JSON_END===", flush=True)
"""


    try:
        # Run container with streaming logs
        container = client.containers.run(
            image=image,
            command=['python', '-u', '-c', python_code],  # -u for unbuffered
            volumes={
                os.path.expanduser('~/.config/earthengine'): {
                    'bind': '/root/.config/earthengine',
                    'mode': 'ro'
                }
            },
            environment={
                'GOOGLE_APPLICATION_CREDENTIALS': '/root/.config/earthengine/credentials',
                'PYTHONUNBUFFERED': '1'  # Force unbuffered output
            },
            detach=True,
            remove=False,
            tty=False  # Disable TTY for better streaming
        )

        print("📋 Container Output (Live):")
        print("-"*60)
        sys.stdout.flush()

        # Stream logs in real-time with immediate flushing
        result_json = None
        capture_json = False

        for chunk in container.logs(stream=True, follow=True, timestamps=False):
            line_str = chunk.decode('utf-8').rstrip('\n')

            # Check for JSON markers
            if '===RESULT_JSON_START===' in line_str:
                capture_json = True
                continue
            elif '===RESULT_JSON_END===' in line_str:
                capture_json = False
                continue

            # Capture JSON result
            if capture_json:
                try:
                    result_json = json.loads(line_str)
                except:
                    pass

            # Print immediately and flush
            print(line_str)
            sys.stdout.flush()  # Force immediate output to Airflow logs

        print("-"*60)
        sys.stdout.flush()

        # Wait for container to finish
        exit_info = container.wait()

        # Remove container now
        container.remove()

        # Check if execution was successful
        if exit_info['StatusCode'] != 0:
            raise Exception(f"Container exited with code {exit_info['StatusCode']}")

        # Parse result
        if result_json and 'asset_ids' in result_json:
            asset_ids = result_json['asset_ids']
            hosting_platform = result_json.get('hosting_platform', 'GEE')
            stac_spec = result_json.get('stac_spec', None)
            print(f"✅ Docker execution successful")
            print(f"   Assets: {asset_ids}")
            print(f"   Platform: {hosting_platform}")
            sys.stdout.flush()
            return {
                'asset_ids': asset_ids,
                'hosting_platform': hosting_platform,
                'stac_spec': stac_spec
            }
        else:
            print("⚠️ No JSON result found, assuming success")
            sys.stdout.flush()
            return {
                'asset_ids': [],
                'hosting_platform': 'GEE',
                'stac_spec': None
            }


    except docker.errors.ContainerError as e:
        print(f"❌ Docker container failed:")
        print(f"   Exit code: {e.exit_status}")
        if e.stderr:
            print(f"   Stderr: {e.stderr.decode('utf-8')}")
        sys.stdout.flush()
        raise Exception(f"Docker execution failed: {e}")

    except docker.errors.ImageNotFound:
        print(f"❌ Docker image not found: {image}")
        print(f"   Please build it first: docker build -t {image} ~/stacd_backend/")
        sys.stdout.flush()
        raise Exception(f"Docker image '{image}' not found")

    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        sys.stdout.flush()
        raise
